### ISSUE TITLE
Fails locally and on heroku with HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.3-bin.zip

### ISSUE THREAD

**Issue by IanVaughan** [tzachz/github-comment-counter#33]
```
Enumerating objects: 1467, done.
Counting objects: 100% (1467/1467), done.
Delta compression using up to 8 threads
Compressing objects: 100% (528/528), done.
Writing objects: 100% (1467/1467), 604.88 KiB | 50.41 MiB/s, done.
Total 1467 (delta 420), reused 1467 (delta 420), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Gradle app detected
remote: -----> Installing JDK 1.7... done
remote: -----> Building Gradle app...
remote: -----> executing ./gradlew stage
remote:        Downloading http://services.gradle.org/distributions/gradle-2.3-bin.zip
remote:
remote:        Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.3-bin.zip
remote:         at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
remote:         at org.gradle.wrapper.Install.createDist(Install.java:47)
remote:         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
remote:         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
remote:        Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.3-bin.zip
remote:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1700)
remote:         at org.gradle.wrapper.Download.downloadInternal(Download.java:59)
remote:         at org.gradle.wrapper.Download.download(Download.java:45)
remote:         at org.gradle.wrapper.Install$1.call(Install.java:60)
remote:         at org.gradle.wrapper.Install$1.call(Install.java:47)
remote:         at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
remote:         ... 3 more
remote:
remote:  !     ERROR: Failed to run Gradle!
remote:        We're sorry this build is failing. If you can't find the issue in application
remote:        code, please submit a ticket so we can help: https://help.heroku.com
remote:        You can also try reverting to the previous version of the buildpack by running:
remote:        $ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-gradle#previous-version
remote:
remote:        Thanks,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Gradle app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to enigmatic-lake-86326.
remote:
To https://git.heroku.com/enigmatic-lake-86326.git
 ! [remote rejected] master -> master (pre-receive hook declined)
```

**Comment by tzachz** [comment]
Thanks for filing! This project is using a very old Gradle version, which is probably the cause for this failure. Even if it isn't, an upgrade should be the first step to make sure we're not troubleshooting a lost cause. 
I'l try upgrading it to latest soon.

**Comment by tzachz** [comment]
Upgraded to Gradle 5.4 (and JDK 1.8). I've tested on a fresh Heroku instance and everything seems to work smoothly. I did have to change the packaging (see details in #34) so instructions for running locally changed a bit (see updated README). 

@IanVaughan you're welcome to give it a try - let me know if you're still experiencing issues.

Thanks!

**Comment by IanVaughan** [comment]
@tzachz wow thanks for the quick response! 
I tested it out and it worked a treat, thanks once again.
